# airship web server postgres->django-uwsgi->nginx
# docker-compose.yml
# refreshed 2017-11-30
 
version: '3'  

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password    #set the password of the db
    volumes:
      - pgdata:/var/lib/postgresql/data/    
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
     - 8080:8080

  app:
    container_name: django-uwsgi
    build: ./code/django-uwsgi
    image: django-uwsgi:test
    restart: always
    depends_on: 
      - db
    volumes:                             #mount a host path to deploy the app dynamically
      - "./code/django-uwsgi/app:/app"
    ports:
      - 9191:9191

  nginx:
    container_name: nginx
    build: ./code/nginx
    image: nginx:test
    depends_on:
      - app
    restart: always
    ports:
      - 80:80
    volumes:
      - "./code/django-uwsgi/app:/app"

volumes:
  pgdata:                            #create a volume of db for backuping
